### PR TITLE
Operators

### PR DESCRIPTION
**Pull request by SamuelMwangiW**
Thanks for the amazing work 👏🏽.

This PR proposes to introduce an decorator pattern to customize the request and response parameters to suit each service provider. 

Am also not sure of the names and went Operator as you call them operators in the [docs](https://sparors.github.io/ussd-docs/docs/machine/#machine-out-manupulate). I was also unsure interface method name therefore I welcome suggestions besides `decorate`.

This allows the developer to define their operator in the config the init the machine in the controller as the docs and everything just works <sup>TM</sup>. 

The Operator only needs to implement `Sparors\Ussd\Contracts\OperatorContract::class`. Samples from https://github.com/sparors/laravel-ussd/issues/22#issuecomment-981152736 are provided but the developer is at liberty to use their own.

If properly set, the following should just work<sup>TM</sup>.

```php
use Sparors\Ussd\Facades\Ussd;

$machine = Ussd:machine()
            ->setInitialState(HelloState::class);

return response()->json($machine->run());

```
This has the added benefit that the same code can be used for different providers and the configured provider is dynamically set in say a middleware 💪

Tests might need to improvement therefore any help is welcome.

Once approved, kindly squash merge 😜

### CODE REVIEW

**Comment by SamuelMwangiW** [comment]
No more commits, should be ready for your review. 

Feel free to close if you have reservations about the PR.

Thanks once again for an amazing package 👏

**Comment by papamarfo** [comment]
Nice work man. I like the idea of the abstraction and supporting multiple providers as well. Why leave the test for us to write though 😂. Just joking

**Comment by SamuelMwangiW** [comment]
> Nice work man. I like the idea of the abstraction and supporting multiple providers as well. Why leave the test for us to write though 😂. Just joking

Thanks buddy for the kind words. I had the feeling that tests were incomplete at the time of writing the comment but has since improved the situation with [6384581](https://github.com/sparors/laravel-ussd/pull/28/commits/6384581df6c082a6d6d19c9b6ee8187be267ad4c) and are open to add tests for any uncovered areas.

**Comment by cybersai** [comment]
Thanks, @SamuelMwangiW for your contribution. However, I would like to remove implementations for operators in the library to prevent us from having to maintain that in the future. Since this is not a major version, I would like for us to prevent making changes to the config file. I would therefor merge this to a different branch and do the changes and let you review if you are okay with it.

**Comment by SamuelMwangiW** [comment]
Thanks @cybersai for your review. 
I also had reservations about the changes to the config file. I would want to see suggestions from developers whose applications are integrating with more than one operator on how they would go about it then we can merge the branch into the next major.
I will however be using the `operators` branch as it makes integrating with a single operator a breeze.
Kudos for your work on this amazing package

**Comment by cybersai** [comment]
Thanks, @SamuelMwangiW, you can check #29 and submit your comments.

**Pull request merged**
